name = "0jewell/prism"
version = "0.1.1"
description = "A ECS library based on reactive systems"
authors = ["0jewell"]
repository = "https://github.com/0jewell/Prism"
license = "MIT"
includes = ["src/**/*.luau", "README.md", "LICENSE", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
TestEZ = { wally = "roblox/testez", version = "^0.4.1" }
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }