name = "0jewell/prism"
version = "0.1.0"
description = "Library based on Celesta"
authors = ["0jewell"]
repository = "https://github.com/0jewell/Prism"
license = "MIT"
includes = ["src", "src/*", "default.project.json", "pesde.toml", "pesde.lock"]

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
TestEZ = { wally = "roblox/testez", version = "^0.4.1" }
Iris = { wally = "sirmallard/iris", version = "2.4.1" }