name: MkDocs Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Configure git credentials
        run: |
          git config user.name prismdoc
          git config user.email prismdoc@example.com

      - name: Release on gh-pages
        run: |
          mkdocs gh-deploy