name: Unit testing

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Run tests
        run: |
          lune run tests/run